### ISSUE TITLE
IndexError

### ISSUE THREAD

**Issue by Butsch94** [vikrambajaj22/Spidey-Focused-Web-Crawler#1]
Hello, 
I always get the following error message with your code. 
What do I have to adjust so that this does not appear?
Unfortunately I can't find the error that triggers the IndexError. 
Thanks in advance. 

Traceback (most recent call last):
  File "C:\Users\schue\Desktop\Webcrawler-A\Spidey-Focused-Web-Crawler-master\spidey.py", line 722, in <module>
    main()
  File "C:\Users\schue\Desktop\Webcrawler-A\Spidey-Focused-Web-Crawler-master\spidey.py", line 708, in main
    crawler.run()
  File "C:\Users\schue\Desktop\Webcrawler-A\Spidey-Focused-Web-Crawler-master\spidey.py", line 167, in run
    item = self.links_to_parse.dequeue()  # get first item (highest promise) from the queue, item = [promise,url]
  File "C:\Users\schue\Desktop\Webcrawler-A\Spidey-Focused-Web-Crawler-master\spidey.py", line 74, in dequeue
    item = self.queue[0]  # item with highest promise
IndexError: list index out of range

**Comment by vikrambajaj22** [comment]
Can you also provide the output of the code from the terminal?

Please verify if the queue has items before the dequeue is attempted. You could try uncommenting the _while_ on line 72.

**Comment by Butsch94** [comment]
Thanks for your quick feedback and your help. I am not so experienced with programming and therefore I am not so good at error handling.

Uncommenting the while on line 72 has worked.
But as you can See, There is no crawlable start page found. 

C:\Users\schue\Desktop\Webcrawler-A\Spidey-Focused-Web-Crawler-master\venv\Scripts\python.exe C:/Users/schue/Desktop/Webcrawler-A/Spidey-Focused-Web-Crawler-master/spidey.py
Enter your query (default: "wildfires california"): 
Enter the number of start pages (default: 10): 
Enter the number of pages to be returned (at least 10, default: 1000): 
Enter the max. no. of links to be fetched from each page (at least 10, default: 25): 
Enter mode 'bfs' or 'focused' (default: 'bfs'): 
Enter the relevance threshold (min: 0, max: 4.75, default: 1): 

Obtaining start pages...


Found 0 crawlable start pages:

Queue:


No exit code appears even after more than an hour.
So I had to stop the run after 2 hours.

-----------------------------------------
I use PyCharm and in the Terminal is only this written:
(venv) C:\Users\schue\Desktop\Webcrawler-A>

-----------------------------------------

When results are found, the current crawl parameters are output in log file. 
Is it possible to extend the crawler so that only the best search result is output directly as Excel? So HTML to Excel. In a "simple" crawler I can do this, but this one is a bit more complex. Which step would be necessary for this?

**Comment by vikrambajaj22** [comment]
Hi, no worries.
To extend the crawler, please feel free to fork the code and add functionality. It should be easy to re-format the output using packages like pandas and write to an Excel using its ExcelWriter.

**Comment by Butsch94** [comment]
Cheers Mate,
But unfortunately I get as already written currently no feedback (Found 0 crawlable start pages:). What could be the reason for this?
Would be great if you could help me with it.
